language: python
python:
- "2.6"
- "2.7"
- pypy
matrix:
  allow_failures:
  - python: pypy
addons:
  apt:
    packages:
    - nasm
    - gcc-multilib
install:
- pip install byteplay
- pip install ply
script:
- nosetests -v

# vim:ts=2 sts=2 sw=2 et
