#!/bin/sh
tmpfile=`mktemp -t 'jtc.XXXXXXXX'` || exit 1
run='python2.4'
[ "q$*" = 'q-X' ] && run=''

trap 'rm -f "$tmpfile"' EXIT
for file in examples/good/*.jl
do
  printf -- '---- %s ----\n' "$file"
  ./jtc "$@" $file 2>&1 -o "$tmpfile" && 
  (
    printf 'OK\n'
    ifile="`printf '%s' "$file" | sed -e 's/[.]jl$/.input/'`"
    ofile="`printf '%s' "$file" | sed -e 's/[.]jl$/.output/'`"
    exec < /dev/null
    [ -r "$ifile" ] && exec < "$ifile"
    $run "$tmpfile" | diff - "$ofile"
  )
  printf '\n'
done

for file in examples/bad/bad*.jl
do
  printf -- '---- %s ----\n' "$file"
  ./jtc $file 2>&1 > /dev/null && printf 'OK\n'
  printf '\n'
done

# vim:ts=2 sw=2 et
