#!/usr/bin/env python
# encoding=UTF-8

# Copyright © 2007-2012 Jakub Wilk <jwilk@jwilk.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import byteplay
import marshal
from sys import argv

def print_code(co):
    print
    print '# %s (%s, %s)' % (co, co.name, co.filename)
    print co.code
    for instr in co.code:
        for arg in instr:
            if isinstance(arg, byteplay.Code):
                print_code(arg)

for name in argv[1:]:
    f = file(name, 'rb');
    f.seek(8)
    co = marshal.load(f);
    co = byteplay.Code.from_code(co)
    print "# Bytecode dumped from %r" % f.name
    print_code(co)

# vim:ts=4 sts=4 sw=4 et
